apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-svc
spec:
    ports:
    - name: demo
      targetPort: {{ .Values.service.port }}
      port: {{ .Values.service.port }}
      protocol: TCP
    selector:
       app: demo
    type: {{ .Values.service.type }}